#!/usr/bin/env bash
# Install PostgreSQL from the PostgreSQL community repository (PGDG) and tune
# it for this node's size.
#
# Usage: database-install.sh [--version 18] [--shared-buffers-pct 25]
#                            [--synchronous-commit on|off]
#
#   --version             PostgreSQL major version (default 18)
#   --shared-buffers-pct  shared_buffers as a share of RAM (default 25)
#   --synchronous-commit  on = durable commits (default), off = commits do
#                         not wait for the WAL flush
#
# Safe to re-run: an existing installation is kept and only the tuning file
# is regenerated (and the server restarted).
source "$(dirname "$0")/../common/lib.sh"

usage() { sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

require_root
load_config
load_db
while (($#)); do
    case $1 in
        --version)            conf_set PG_VERSION "$2"; shift 2 ;;
        --shared-buffers-pct) conf_set PG_SHARED_BUFFERS_PCT "$2"; shift 2 ;;
        --synchronous-commit) conf_set PG_SYNCHRONOUS_COMMIT "$2"; shift 2 ;;
        -h|--help)            usage ;;
        *) warn "unknown option $1"; usage 1 ;;
    esac
done
[[ $PG_VERSION =~ ^[0-9]+$ ]] || die "--version must be a major version such as 18"

FAMILY=$(os_family)
SERVICE=$(db_service)
claim_database postgresql
install_payload

# ---------------------------------------------------------------------------
# 1. Packages
# ---------------------------------------------------------------------------
base_packages

FRESH_INSTALL=0
if [[ ! -x $(pg_bindir)/postgres ]]; then
    FRESH_INSTALL=1
    log "installing PostgreSQL $PG_VERSION from the PGDG repository"
    case $FAMILY in
        debian)
            pkg_install postgresql-common
            /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
            # creates and starts the cluster $PG_VERSION/main
            pkg_install "postgresql-$PG_VERSION" "postgresql-client-$PG_VERSION"
            ;;
        rhel)
            # shellcheck disable=SC1091
            . /etc/os-release
            rpm -q pgdg-redhat-repo &>/dev/null || dnf install -y -q \
                "https://download.postgresql.org/pub/repos/yum/reporpms/EL-${VERSION_ID%%.*}-$(uname -m)/pgdg-redhat-repo-latest.noarch.rpm"
            dnf -qy module disable postgresql 2>/dev/null || true
            pkg_install "postgresql$PG_VERSION-server" "postgresql$PG_VERSION-contrib"
            "$(pg_bindir)/postgresql-$PG_VERSION-setup" initdb
            # local TCP connections authenticate with passwords (default: ident)
            sed -i -E 's/^(host\s+all\s+all\s+\S+\s+)ident/\1scram-sha-256/' "/var/lib/pgsql/$PG_VERSION/data/pg_hba.conf"
            ;;
    esac
else
    log "PostgreSQL $PG_VERSION is already installed"
fi

systemctl enable "$SERVICE" &>/dev/null
systemctl start "$SERVICE"
db_wait
DATADIR=$(pg_local -At -c 'SHOW data_directory')
CONFFILE=$(pg_local -At -c 'SHOW config_file')

# The postgres superuser gets a password: HammerDB connects with it over TCP
# to create the benchmark user and database.
if [[ -r $PG_ADMIN_CNF ]]; then
    ADMIN_PASS=$(cnf_value "$PG_ADMIN_CNF" password)
else
    ADMIN_PASS=$(random_password)
fi
pg_local -c "ALTER ROLE postgres PASSWORD '$ADMIN_PASS'"
write_pg_cnf "$PG_ADMIN_CNF" postgres "$ADMIN_PASS" root 0600

# ---------------------------------------------------------------------------
# 2. Tuning for this node
# ---------------------------------------------------------------------------
MEM_MB=$(mem_total_mb)
CPUS=$(cpu_count)
SB_MB=$(( MEM_MB * PG_SHARED_BUFFERS_PCT / 100 / 128 * 128 ))
(( SB_MB >= 128 )) || SB_MB=128
# WAL between checkpoints: twice shared_buffers, 2 to 64 GB (the counterpart
# of the InnoDB redo log capacity)
WAL_MB=$(( SB_MB * 2 ))
(( WAL_MB < 2048 )) && WAL_MB=2048
(( WAL_MB > 65536 )) && WAL_MB=65536
# page cache PostgreSQL can expect: what shared_buffers and HammerDB leave
CACHE_MB=$(( MEM_MB * 60 / 100 - SB_MB ))
(( CACHE_MB > SB_MB )) || CACHE_MB=$SB_MB
MAINT_MB=$(( MEM_MB / 16 ))
(( MAINT_MB > 2048 )) && MAINT_MB=2048
disk_class "$DATADIR"
case $DISK_CLASS in
    hdd)  RANDOM_PAGE_COST=4;   IO_CONCURRENCY=2 ;;
    nvme) RANDOM_PAGE_COST=1.1; IO_CONCURRENCY=256 ;;
    *)    RANDOM_PAGE_COST=1.1; IO_CONCURRENCY=200 ;;
esac

case $FAMILY in
    # Debian's postgresql.conf includes conf.d/
    debian) CNF="$(dirname "$CONFFILE")/conf.d/zz-parmaham.conf" ;;
    rhel)   CNF="$DATADIR/zz-parmaham.conf"
            grep -q "^include_if_exists = 'zz-parmaham.conf'" "$CONFFILE" \
                || echo "include_if_exists = 'zz-parmaham.conf'" >> "$CONFFILE" ;;
esac
log "writing $CNF (RAM ${MEM_MB}MB, ${CPUS} CPUs, $DISK_CLASS storage)"
install -d -o postgres -g postgres "$(dirname "$CNF")"
cat > "$CNF" <<EOF
# Generated by Parma Ham database-install.sh on $(date -u '+%F %T') UTC.
# Node: ${MEM_MB} MB RAM, ${CPUS} CPUs, data directory on $DISK_NAME ($DISK_CLASS).
# Re-run database-install.sh to regenerate; local changes will be lost.
max_connections = 300
shared_buffers = ${SB_MB}MB
effective_cache_size = ${CACHE_MB}MB
maintenance_work_mem = ${MAINT_MB}MB
huge_pages = try

# durability and WAL (WAL archiving stays off, so a months-long run cannot
# fill the disk)
synchronous_commit = $PG_SYNCHRONOUS_COMMIT
max_wal_size = ${WAL_MB}MB
min_wal_size = $(( WAL_MB / 4 ))MB
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9

# storage
random_page_cost = $RANDOM_PAGE_COST
effective_io_concurrency = $IO_CONCURRENCY
track_io_timing = on

# autovacuum must keep up with TPROC-C's updates for months
autovacuum_vacuum_cost_limit = 2000

# statement counts for the dashboard (queries per second)
shared_preload_libraries = 'pg_stat_statements'
EOF
chown postgres:postgres "$CNF"

install_os_tuning "$SERVICE"
log "restarting $SERVICE"
systemctl restart "$SERVICE"
db_wait

# ---------------------------------------------------------------------------
# 3. Accounts for HammerDB and the dashboard
# ---------------------------------------------------------------------------
if [[ -r $PG_BENCH_CNF ]]; then BENCH_PASS=$(cnf_value "$PG_BENCH_CNF" password); else BENCH_PASS=$(random_password); fi
if [[ -r $PG_MONITOR_CNF ]]; then MON_PASS=$(cnf_value "$PG_MONITOR_CNF" password); else MON_PASS=$(random_password); fi
pg_local -d postgres <<EOF
SET client_min_messages = warning;
SELECT format('CREATE ROLE %I LOGIN', r) FROM unnest(ARRAY['$PG_BENCH_USER', '$PG_MONITOR_USER']) r
 WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) \gexec
ALTER ROLE $PG_BENCH_USER LOGIN PASSWORD '$BENCH_PASS';
ALTER ROLE $PG_MONITOR_USER LOGIN PASSWORD '$MON_PASS';
GRANT pg_monitor TO $PG_MONITOR_USER;
EOF
write_pg_cnf "$PG_BENCH_CNF" "$PG_BENCH_USER" "$BENCH_PASS" "$PMH_USER" 0640
write_pg_cnf "$PG_MONITOR_CNF" "$PG_MONITOR_USER" "$MON_PASS" root 0600
# re-running on an existing schema: refresh the dashboard's access
if db_schema_exists; then db_after_build >/dev/null; fi

log "PostgreSQL $(db_admin 'SHOW server_version') is running (shared_buffers ${SB_MB}MB, max_wal_size ${WAL_MB}MB)"
[[ $FRESH_INSTALL == 1 ]] && log "superuser credentials are in $PG_ADMIN_CNF"
log "next step: $(dirname "$0")/database-generate.sh"
