# shellcheck shell=bash
# Database plug-in for PostgreSQL (community packages from PGDG). Sourced by
# common/lib.sh load_db; mysql/lib/db.sh describes the interface.
# orioledb/ and pgrust/ build on it: they override db_service, pg_bindir,
# db_procmem_spec, and the tuning through PG_PRELOAD and pg_extra_conf.
#
# Credential files hold host=, port=, user=, password= lines.

DB_LABEL=${DB_LABEL:-PostgreSQL}
PG_ADMIN_CNF=$PMH_ETC/$PMH_DB-admin.cnf      # postgres superuser, 0600 root
PG_BENCH_CNF=$PMH_ETC/$PMH_DB-bench.cnf      # hammerdb user, 0640 root:parmaham
PG_MONITOR_CNF=$PMH_ETC/$PMH_DB-monitor.cnf  # dashboard user, 0600 root
# libraries preloaded by the tuning file (pg_stat_statements: queries/s on the dashboard)
PG_PRELOAD=${PG_PRELOAD-pg_stat_statements}
PG_BENCH_USER=hammerdb
PG_MONITOR_USER=parmaham_mon
PG_BENCH_DB=tpcc

db_service() {
    case $(os_family) in
        debian) echo "postgresql@$PG_VERSION-main" ;;
        rhel)   echo "postgresql-$PG_VERSION" ;;
    esac
}

pg_bindir() {
    case $(os_family) in
        debian) echo "/usr/lib/postgresql/$PG_VERSION/bin" ;;
        rhel)   echo "/usr/pgsql-$PG_VERSION/bin" ;;
    esac
}

# psql with the credentials of a cnf file: pg_psql CNF [psql options]
pg_psql() {
    local cnf=$1; shift
    PGPASSWORD=$(cnf_value "$cnf" password) PGCONNECT_TIMEOUT=10 \
        "$(pg_bindir)/psql" -X -q -v ON_ERROR_STOP=1 -h "$(cnf_value "$cnf" host)" \
        -p "$(cnf_value "$cnf" port)" -U "$(cnf_value "$cnf" user)" "$@"
}

# psql as the postgres OS user (peer authentication), for the installer
pg_local() { (cd / && runuser -u postgres -- "$(pg_bindir)/psql" -X -q -v ON_ERROR_STOP=1 "$@"); }

db_admin() { if (($#)); then pg_psql "$PG_ADMIN_CNF" -d postgres -At -F $'\t' -c "$1"; else pg_psql "$PG_ADMIN_CNF" -d postgres; fi; }
db_bench() { if (($#)); then pg_psql "$PG_BENCH_CNF" -d "$PG_BENCH_DB" -At -F $'\t' -c "$1"; else pg_psql "$PG_BENCH_CNF" -d "$PG_BENCH_DB"; fi; }

# write_pg_cnf file user password owner_group mode
write_pg_cnf() {
    printf 'host=localhost\nport=%s\nuser=%s\npassword=%s\n' "${PG_PORT:-5432}" "$2" "$3" | write_cnf "$1" "$4" "$5"
}

db_wait() {
    local i
    for i in $(seq 1 120); do
        if runuser -u postgres -- "$(pg_bindir)/pg_isready" -q -h localhost -p "${PG_PORT:-5432}"; then return 0; fi
        sleep 2
    done
    die "PostgreSQL did not become available"
}

# Export the PMH_DB_* variables used by the HammerDB Tcl scripts. The
# superuser is only needed (and only readable, by root) to build the schema.
hdb_env() {
    [[ -r $PG_BENCH_CNF ]] || die "$PG_BENCH_CNF not found - run database-install.sh first"
    export PMH_DB_HOST=localhost
    PMH_DB_PORT=$(cnf_value "$PG_BENCH_CNF" port)
    PMH_DB_USER=$(cnf_value "$PG_BENCH_CNF" user)
    PMH_DB_PASS=$(cnf_value "$PG_BENCH_CNF" password)
    export PMH_DB_PORT PMH_DB_USER PMH_DB_PASS
    export PMH_DB_NAME=$PG_BENCH_DB
    if [[ -r $PG_ADMIN_CNF ]]; then
        PMH_DB_SUPERUSER=$(cnf_value "$PG_ADMIN_CNF" user)
        PMH_DB_SUPERPASS=$(cnf_value "$PG_ADMIN_CNF" password)
        export PMH_DB_SUPERUSER PMH_DB_SUPERPASS
    fi
}

db_schema_exists() { [[ -n $(db_admin "SELECT 1 FROM pg_database WHERE datname = '$PG_BENCH_DB'") ]]; }
db_drop_schema()   { db_admin "DROP DATABASE \"$PG_BENCH_DB\" WITH (FORCE)"; }
db_version()       { db_bench 'SHOW server_version'; }
db_schema_size_mb() { db_admin "SELECT pg_database_size('$PG_BENCH_DB') / 1048576"; }

# HammerDB's history table has no key. Add a BIGINT identity primary key so
# the purge job can delete old history rows by key range (HammerDB inserts
# name their columns, so the extra column is filled automatically).
# orioledb/lib/db.sh replaces this.
pg_history_key() {
    log "adding a BIGINT identity primary key to history"
    db_bench "ALTER TABLE history ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
}

db_after_build() {
    pg_history_key
    db_bench "VACUUM (ANALYZE) history"
    # dashboard: shared buffer and statement statistics where the server has
    # these extensions
    local ext
    for ext in pg_buffercache pg_stat_statements; do
        pg_psql "$PG_ADMIN_CNF" -d "$PG_BENCH_DB" -c "CREATE EXTENSION IF NOT EXISTS $ext" 2>/dev/null \
            || warn "extension $ext is not available: the dashboard shows less detail"
    done
    # and read access to the benchmark tables (also those created later,
    # such as the purge log)
    pg_psql "$PG_ADMIN_CNF" -d "$PG_BENCH_DB" <<EOF
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $PG_MONITOR_USER;
ALTER DEFAULT PRIVILEGES FOR ROLE $PG_BENCH_USER IN SCHEMA public GRANT SELECT ON TABLES TO $PG_MONITOR_USER;
EOF
}

db_purge_install() {
    db_bench < "$PMH_HOME/postgresql/lib/purge.sql"
    # first watermark, so data from now on can be purged after the retention period
    db_bench "CALL parmaham_purge_mark()"
}

db_purge_run() {
    # the procedure commits after every batch; its summary is a NOTICE
    pg_psql "$PG_BENCH_CNF" -d "$PG_BENCH_DB" -c "CALL parmaham_purge($1, $2)"
}

# The postgres superuser gets a password: HammerDB connects with it over TCP
# to create the benchmark user and database.
pg_set_admin_password() {
    local pass
    if [[ -r $PG_ADMIN_CNF ]]; then pass=$(cnf_value "$PG_ADMIN_CNF" password); else pass=$(random_password); fi
    pg_local -c "ALTER ROLE postgres PASSWORD '$pass'"
    write_pg_cnf "$PG_ADMIN_CNF" postgres "$pass" root 0600
}

# Write the tuning for this node to file $1; $2 is the data directory (its
# disk type decides the I/O settings). Sets SB_MB and WAL_MB. Variants add
# or override settings with pg_extra_conf (printed last; the last value wins).
pg_write_tuning() {
    local cnf=$1 datadir=$2 cache_mb maint_mb random_page_cost io_concurrency
    MEM_MB=$(mem_total_mb)
    CPUS=$(cpu_count)
    SB_MB=$(( MEM_MB * PG_SHARED_BUFFERS_PCT / 100 / 128 * 128 ))
    (( SB_MB >= 128 )) || SB_MB=128
    # WAL between checkpoints: twice shared_buffers, 2 to 64 GB (the
    # counterpart of the InnoDB redo log capacity)
    WAL_MB=$(( SB_MB * 2 ))
    (( WAL_MB < 2048 )) && WAL_MB=2048
    (( WAL_MB > 65536 )) && WAL_MB=65536
    # page cache PostgreSQL can expect: what shared_buffers and HammerDB leave
    cache_mb=$(( MEM_MB * 60 / 100 - SB_MB ))
    (( cache_mb > SB_MB )) || cache_mb=$SB_MB
    maint_mb=$(( MEM_MB / 16 ))
    (( maint_mb > 2048 )) && maint_mb=2048
    disk_class "$datadir"
    case $DISK_CLASS in
        hdd)  random_page_cost=4;   io_concurrency=2 ;;
        nvme) random_page_cost=1.1; io_concurrency=256 ;;
        *)    random_page_cost=1.1; io_concurrency=200 ;;
    esac
    log "writing $cnf (RAM ${MEM_MB}MB, ${CPUS} CPUs, $DISK_CLASS storage)"
    # only create the directory: install -d would also reset the mode of an
    # existing one, and the data directory must stay 0700
    [[ -d $(dirname "$cnf") ]] || install -d -o postgres -g postgres "$(dirname "$cnf")"
    cat > "$cnf" <<EOF
# Generated by Parma Ham database-install.sh on $(date -u '+%F %T') UTC.
# Node: ${MEM_MB} MB RAM, ${CPUS} CPUs, data directory on $DISK_NAME ($DISK_CLASS).
# Re-run database-install.sh to regenerate; local changes will be lost.
max_connections = 300
shared_buffers = ${SB_MB}MB
effective_cache_size = ${cache_mb}MB
maintenance_work_mem = ${maint_mb}MB
huge_pages = try

# durability and WAL (WAL archiving stays off, so a months-long run cannot
# fill the disk)
synchronous_commit = $PG_SYNCHRONOUS_COMMIT
max_wal_size = ${WAL_MB}MB
min_wal_size = $(( WAL_MB / 4 ))MB
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9

# storage
random_page_cost = $random_page_cost
effective_io_concurrency = $io_concurrency
track_io_timing = on

# autovacuum must keep up with TPROC-C's updates for months
autovacuum_vacuum_cost_limit = 2000

# statement counts for the dashboard (queries per second)
shared_preload_libraries = '$PG_PRELOAD'
EOF
    if declare -F pg_extra_conf >/dev/null; then
        { echo; pg_extra_conf; } >> "$cnf"
    fi
    chown postgres:postgres "$cnf"
}

# Benchmark and monitoring roles and their credential files
pg_create_accounts() {
    local bench_pass mon_pass
    if [[ -r $PG_BENCH_CNF ]]; then bench_pass=$(cnf_value "$PG_BENCH_CNF" password); else bench_pass=$(random_password); fi
    if [[ -r $PG_MONITOR_CNF ]]; then mon_pass=$(cnf_value "$PG_MONITOR_CNF" password); else mon_pass=$(random_password); fi
    pg_local -d postgres <<EOF
SET client_min_messages = warning;
SELECT format('CREATE ROLE %I LOGIN', r) FROM unnest(ARRAY['$PG_BENCH_USER', '$PG_MONITOR_USER']) r
 WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) \gexec
ALTER ROLE $PG_BENCH_USER LOGIN PASSWORD '$bench_pass';
ALTER ROLE $PG_MONITOR_USER LOGIN PASSWORD '$mon_pass';
GRANT pg_monitor TO $PG_MONITOR_USER;
EOF
    write_pg_cnf "$PG_BENCH_CNF" "$PG_BENCH_USER" "$bench_pass" "$PMH_USER" 0640
    write_pg_cnf "$PG_MONITOR_CNF" "$PG_MONITOR_USER" "$mon_pass" root 0600
    # re-running on an existing schema: refresh the dashboard's access
    if db_schema_exists; then db_after_build >/dev/null; fi
}

# every server process is called postgres; count the whole service so the
# CPU of connections that have ended is included
db_procmem_spec() { echo "postgres=$(db_service).service+postgres"; }
