# shellcheck shell=bash
# Database plug-in for PostgreSQL (community packages from PGDG). Sourced by
# common/lib.sh load_db; mysql/lib/db.sh describes the interface.
#
# Credential files hold host=, port=, user=, password= lines.

DB_LABEL=PostgreSQL
PG_ADMIN_CNF=$PMH_ETC/postgresql-admin.cnf      # postgres superuser, 0600 root
PG_BENCH_CNF=$PMH_ETC/postgresql-bench.cnf      # hammerdb user, 0640 root:parmaham
PG_MONITOR_CNF=$PMH_ETC/postgresql-monitor.cnf  # dashboard user, 0600 root
PG_BENCH_USER=hammerdb
PG_MONITOR_USER=parmaham_mon
PG_BENCH_DB=tpcc

db_service() {
    case $(os_family) in
        debian) echo "postgresql@$PG_VERSION-main" ;;
        rhel)   echo "postgresql-$PG_VERSION" ;;
    esac
}

pg_bindir() {
    case $(os_family) in
        debian) echo "/usr/lib/postgresql/$PG_VERSION/bin" ;;
        rhel)   echo "/usr/pgsql-$PG_VERSION/bin" ;;
    esac
}

# psql with the credentials of a cnf file: pg_psql CNF [psql options]
pg_psql() {
    local cnf=$1; shift
    PGPASSWORD=$(cnf_value "$cnf" password) PGCONNECT_TIMEOUT=10 \
        "$(pg_bindir)/psql" -X -q -v ON_ERROR_STOP=1 -h "$(cnf_value "$cnf" host)" \
        -p "$(cnf_value "$cnf" port)" -U "$(cnf_value "$cnf" user)" "$@"
}

# psql as the postgres OS user (peer authentication), for the installer
pg_local() { (cd / && runuser -u postgres -- "$(pg_bindir)/psql" -X -q -v ON_ERROR_STOP=1 "$@"); }

db_admin() { if (($#)); then pg_psql "$PG_ADMIN_CNF" -d postgres -At -F $'\t' -c "$1"; else pg_psql "$PG_ADMIN_CNF" -d postgres; fi; }
db_bench() { if (($#)); then pg_psql "$PG_BENCH_CNF" -d "$PG_BENCH_DB" -At -F $'\t' -c "$1"; else pg_psql "$PG_BENCH_CNF" -d "$PG_BENCH_DB"; fi; }

# write_pg_cnf file user password owner_group mode
write_pg_cnf() {
    printf 'host=localhost\nport=%s\nuser=%s\npassword=%s\n' "${PG_PORT:-5432}" "$2" "$3" | write_cnf "$1" "$4" "$5"
}

db_wait() {
    local i
    for i in $(seq 1 120); do
        if runuser -u postgres -- "$(pg_bindir)/pg_isready" -q -h localhost -p "${PG_PORT:-5432}"; then return 0; fi
        sleep 2
    done
    die "PostgreSQL did not become available"
}

# Export the PMH_DB_* variables used by the HammerDB Tcl scripts. The
# superuser is only needed (and only readable, by root) to build the schema.
hdb_env() {
    [[ -r $PG_BENCH_CNF ]] || die "$PG_BENCH_CNF not found - run database-install.sh first"
    export PMH_DB_HOST=localhost
    PMH_DB_PORT=$(cnf_value "$PG_BENCH_CNF" port)
    PMH_DB_USER=$(cnf_value "$PG_BENCH_CNF" user)
    PMH_DB_PASS=$(cnf_value "$PG_BENCH_CNF" password)
    export PMH_DB_PORT PMH_DB_USER PMH_DB_PASS
    export PMH_DB_NAME=$PG_BENCH_DB
    if [[ -r $PG_ADMIN_CNF ]]; then
        PMH_DB_SUPERUSER=$(cnf_value "$PG_ADMIN_CNF" user)
        PMH_DB_SUPERPASS=$(cnf_value "$PG_ADMIN_CNF" password)
        export PMH_DB_SUPERUSER PMH_DB_SUPERPASS
    fi
}

db_schema_exists() { [[ -n $(db_admin "SELECT 1 FROM pg_database WHERE datname = '$PG_BENCH_DB'") ]]; }
db_drop_schema()   { db_admin "DROP DATABASE \"$PG_BENCH_DB\" WITH (FORCE)"; }
db_version()       { db_bench 'SHOW server_version'; }
db_schema_size_mb() { db_admin "SELECT pg_database_size('$PG_BENCH_DB') / 1048576"; }

db_after_build() {
    # HammerDB's history table has no key. Add a BIGINT identity primary key
    # so the purge job can delete old history rows by key range (HammerDB
    # inserts name their columns, so the extra column is filled automatically).
    log "adding a BIGINT identity primary key to history"
    db_bench "ALTER TABLE history ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    db_bench "VACUUM (ANALYZE) history"
    # dashboard: read access to the benchmark tables (also those created
    # later, such as the purge log) and shared buffer statistics
    pg_psql "$PG_ADMIN_CNF" -d "$PG_BENCH_DB" <<EOF
CREATE EXTENSION IF NOT EXISTS pg_buffercache;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $PG_MONITOR_USER;
ALTER DEFAULT PRIVILEGES FOR ROLE $PG_BENCH_USER IN SCHEMA public GRANT SELECT ON TABLES TO $PG_MONITOR_USER;
EOF
}

db_purge_install() {
    db_bench < "$PMH_HOME/postgresql/lib/purge.sql"
    # first watermark, so data from now on can be purged after the retention period
    db_bench "CALL parmaham_purge_mark()"
}

db_purge_run() {
    # the procedure commits after every batch; its summary is a NOTICE
    pg_psql "$PG_BENCH_CNF" -d "$PG_BENCH_DB" -c "CALL parmaham_purge($1, $2)"
}

# every server process is called postgres; count the whole service so the
# CPU of connections that have ended is included
db_procmem_spec() { echo "postgres=$(db_service).service+postgres"; }
