#!/usr/bin/env bash
# Install MariaDB Server and tune it for this node's size.
#
# Usage: database-install.sh [--version 13.0] [--buffer-pool-pct 60]
#                            [--binlog 0|1] [--flush-log-at-trx-commit 1|2]
#
#   --version  MariaDB release series from the MariaDB Foundation repository
#              (default 13.0, the newest stable; 12.3 and 11.8 are LTS)
#
# Safe to re-run: an existing installation is kept and only the tuning file
# is regenerated (and the server restarted).
source "$(dirname "$0")/../common/lib.sh"

usage() { sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

require_root
load_config
load_db
while (($#)); do
    case $1 in
        --version)                 conf_set MARIADB_VERSION "$2"; shift 2 ;;
        --buffer-pool-pct)         conf_set MYSQL_BUFFER_POOL_PCT "$2"; shift 2 ;;
        --binlog)                  conf_set MYSQL_BINLOG "$2"; shift 2 ;;
        --flush-log-at-trx-commit) conf_set MYSQL_FLUSH_LOG_AT_TRX_COMMIT "$2"; shift 2 ;;
        -h|--help)                 usage ;;
        *) warn "unknown option $1"; usage 1 ;;
    esac
done

SERVICE=$(db_service)
claim_database mariadb
install_payload

# ---------------------------------------------------------------------------
# 1. Packages
# ---------------------------------------------------------------------------
base_packages

FRESH_INSTALL=0
if ! command -v mariadbd &>/dev/null; then
    command -v mysqld &>/dev/null && die "another MySQL server is installed on this node"
    FRESH_INSTALL=1
    log "enabling the MariaDB $MARIADB_VERSION repository"
    curl -fsSL https://r.mariadb.com/downloads/mariadb_repo_setup \
        | bash -s -- --mariadb-server-version="mariadb-$MARIADB_VERSION" --skip-maxscale --skip-tools
    case $(os_family) in
        debian) apt-get update -q; pkg_install mariadb-server mariadb-client ;;
        rhel)   dnf module disable -y -q mariadb mysql 2>/dev/null || true
                pkg_install MariaDB-server MariaDB-client ;;
    esac
    systemctl enable --now "$SERVICE"
    # root@localhost authenticates with unix_socket; add a password as well so
    # the credentials file works the same way as for MySQL
    ROOT_PASS=$(random_password)
    mariadb -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED VIA unix_socket OR mysql_native_password USING PASSWORD('$ROOT_PASS')"
    MYSQL_SOCKET=""
    write_client_cnf "$MYSQL_ADMIN_CNF" root "$ROOT_PASS" root 0600
    [[ -e /root/.my.cnf ]] || ln -s "$MYSQL_ADMIN_CNF" /root/.my.cnf
else
    log "MariaDB is already installed: $(mariadbd --version)"
    [[ -r $MYSQL_ADMIN_CNF ]] || die "MariaDB is installed but $MYSQL_ADMIN_CNF is missing. Create it with root credentials ([client] user=, password=) and re-run."
fi

systemctl enable "$SERVICE" &>/dev/null
systemctl start "$SERVICE"
db_wait
MYSQL_SOCKET=$(db_admin 'SELECT @@socket')
DATADIR=$(db_admin 'SELECT @@datadir')
conf_set MYSQL_SOCKET "$MYSQL_SOCKET"
write_client_cnf "$MYSQL_ADMIN_CNF" "$(cnf_value "$MYSQL_ADMIN_CNF" user)" "$(cnf_value "$MYSQL_ADMIN_CNF" password)" root 0600

# ---------------------------------------------------------------------------
# 2. Tuning for this node (same sizing as MySQL)
# ---------------------------------------------------------------------------
mysql_sizing "$DATADIR"

if [[ $MYSQL_BINLOG == 1 ]]; then
    BINLOG_CFG="log_bin = binlog
binlog_expire_logs_seconds = $MYSQL_BINLOG_EXPIRE_SECONDS
sync_binlog = 1"
else
    BINLOG_CFG="skip_log_bin"
fi

CNF="$(mysql_conf_dir)/zz-parmaham.cnf"
log "writing $CNF (RAM ${MEM_MB}MB, ${CPUS} CPUs, $DISK_CLASS storage)"
# MariaDB differences: the redo log is sized with innodb_log_file_size, data
# files already use O_DIRECT (innodb_flush_method is deprecated), and
# innodb_numa_interleave does not exist.
cat > "$CNF" <<EOF
# Generated by Parma Ham database-install.sh on $(date -u '+%F %T') UTC.
# Node: ${MEM_MB} MB RAM, ${CPUS} CPUs, datadir on $DISK_NAME ($DISK_CLASS).
# Re-run database-install.sh to regenerate; local changes will be lost.
[mariadbd]
skip_name_resolve = ON
max_connections = 1000
table_open_cache = 4000

innodb_buffer_pool_size = ${BP_MB}M
innodb_log_file_size = ${REDO_MB}M
innodb_log_buffer_size = 64M
innodb_flush_log_at_trx_commit = $MYSQL_FLUSH_LOG_AT_TRX_COMMIT
innodb_io_capacity = $IO_CAP
innodb_io_capacity_max = $IO_CAP_MAX
innodb_read_io_threads = $IO_THREADS
innodb_write_io_threads = $IO_THREADS
innodb_open_files = 4000

$BINLOG_CFG
EOF

install_os_tuning "$SERVICE"
log "restarting $SERVICE"
systemctl restart "$SERVICE"
db_wait

# ---------------------------------------------------------------------------
# 3. Accounts for HammerDB and the dashboard
# ---------------------------------------------------------------------------
mysql_create_accounts "GRANT PROCESS ON *.* TO '$MYSQL_MONITOR_USER'@'localhost';"

log "MariaDB $(db_admin 'SELECT VERSION()') is running (buffer pool ${BP_MB}MB, redo ${REDO_MB}MB, io_capacity $IO_CAP)"
[[ $FRESH_INSTALL == 1 ]] && log "root credentials are in $MYSQL_ADMIN_CNF (linked from /root/.my.cnf)"
log "next step: $(dirname "$0")/database-generate.sh"
