# shellcheck shell=bash
# Database plug-in for OrioleDB: PostgreSQL with OrioleDB's patches, built
# from source, and the orioledb extension as the default table access
# method. Built on the PostgreSQL plug-in (postgresql/lib/db.sh).

DB_LABEL=OrioleDB
# the dashboard's statement counts as on PostgreSQL
PG_PRELOAD="orioledb,pg_stat_statements"
# shellcheck disable=SC1091
source "$PMH_SRC/postgresql/lib/db.sh"

ORIOLEDB_PREFIX=/opt/orioledb/$ORIOLEDB_PG_MAJOR
ORIOLEDB_DATADIR=/var/lib/orioledb/$ORIOLEDB_PG_MAJOR/data

db_service()      { echo orioledb; }
pg_bindir()       { echo "$ORIOLEDB_PREFIX/bin"; }
db_procmem_spec() { echo "postgres=orioledb.service+postgres"; }

# HammerDB's PostgreSQL driver (Pgtcl) loads libpq.so.5, which the source
# build installs outside the library path: link it into HammerDB's private
# library directory
db_hammerdb_libs() {
    install -d "$1"
    ln -sfn "$ORIOLEDB_PREFIX/lib/libpq.so.5" "$1/libpq.so.5"
}

# Adding the history key with ALTER TABLE rewrites the whole table in one
# statement; on OrioleDB beta19 that backend grew past the memory of a 4 GB
# node (OOM-killed at 2.7 GB for 6 million rows). Copy the rows into a new
# table that has the key instead, 10 warehouses per transaction, and swap it in.
pg_history_key() {
    [[ -z $(db_bench "SELECT 1 FROM information_schema.columns WHERE table_name = 'history' AND column_name = 'id'") ]] || return 0
    local cols max w
    cols=$(db_bench "SELECT string_agg(column_name, ', ' ORDER BY ordinal_position) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'history'")
    max=$(db_bench "SELECT max(w_id) FROM warehouse")
    log "adding a BIGINT identity primary key to history (copying it, 10 warehouses per transaction)"
    db_bench "DROP TABLE IF EXISTS history_new"
    db_bench "CREATE TABLE history_new (LIKE history INCLUDING DEFAULTS)"
    db_bench "ALTER TABLE history_new ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    for ((w = 1; w <= max; w += 10)); do
        db_bench "INSERT INTO history_new ($cols) SELECT $cols FROM history WHERE h_w_id BETWEEN $w AND $((w + 9))" >/dev/null
    done
    db_bench < <(printf 'BEGIN;\nDROP TABLE history;\nALTER TABLE history_new RENAME TO history;\nCOMMIT;\n') >/dev/null
}

# OrioleDB tables keep their pages in OrioleDB's own buffer pool
# (orioledb.main_buffers); shared_buffers then only holds the system catalogs,
# so the memory PostgreSQL would give shared_buffers goes to main_buffers.
pg_extra_conf() {
    cat <<EOF
# OrioleDB: every new table uses the orioledb access method
default_table_access_method = 'orioledb'
orioledb.main_buffers = ${SB_MB}MB
shared_buffers = 256MB
EOF
}
